// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8CRmqvLe_SDa0ehEqEQ9W2nNyQg5mr-0',
    appId: '1:493148385669:web:eb19e950a769ca707754ec',
    messagingSenderId: '493148385669',
    projectId: 'chatapp-17de5',
    authDomain: 'chatapp-17de5.firebaseapp.com',
    storageBucket: 'chatapp-17de5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyPA0LyYk_6DSDOQl_lbEpTgxQmTihBIY',
    appId: '1:493148385669:android:681807ce7e3e88327754ec',
    messagingSenderId: '493148385669',
    projectId: 'chatapp-17de5',
    storageBucket: 'chatapp-17de5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2m8XlkIgdkMy5CEsnK0h7AeySrthq5F0',
    appId: '1:493148385669:ios:881ef10c8ec037fd7754ec',
    messagingSenderId: '493148385669',
    projectId: 'chatapp-17de5',
    storageBucket: 'chatapp-17de5.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );
}
